<?php
//hook_init()
function snow_init(){
  #drupal_set_message("Hello again");
  global $base_path;
  $path = $base_path.drupal_get_path('module', 'snow');
  drupal_add_js("var path='$path';","inline");
  drupal_add_js('http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js');
  drupal_add_js(drupal_get_path('module', 'snow')."/snowfall.jquery_new.js");
  drupal_add_js(drupal_get_path('module', 'snow')."/snow_settings.js");
}